// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package po

import (
	"time"
)

const TableNameConfIns = "conf_ins"

// ConfIns mapped from table <conf_ins>
type ConfIns struct {
	ID        int64     `gorm:"column:id;primaryKey;autoIncrement:true"`
	InsCode   string    `gorm:"column:ins_code;not null;comment:实例唯一编码"`
	InsName   string    `gorm:"column:ins_name;not null;comment:实例名称"`
	TypeID    int32     `gorm:"column:type_id;not null;comment:类型ID，关联conf_type表的id"`
	CreatedBy string    `gorm:"column:created_by"`
	UpdatedBy string    `gorm:"column:updated_by"`
	Remark    string    `gorm:"column:remark;comment:备注"`
	CreatedAt time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP;comment:创建时间"`
	UpdatedAt time.Time `gorm:"column:updated_at;default:CURRENT_TIMESTAMP;comment:更新时间"`
	Valid     int32     `gorm:"column:valid;not null;default:1;comment:逻辑删除标记，1有效0无效"`
}

// TableName ConfIns's table name
func (*ConfIns) TableName() string {
	return TableNameConfIns
}
