// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package po

import (
	"time"
)

const TableNameConfInsLabel = "conf_ins_label"

// ConfInsLabel mapped from table <conf_ins_label>
type ConfInsLabel struct {
	ID         int64     `gorm:"column:id;primaryKey;autoIncrement:true"`
	InsID      int64     `gorm:"column:ins_id;not null;comment:实体ID，关联conf_ins表的id"`
	LabelKey   string    `gorm:"column:label_key;not null"`
	LabelValue string    `gorm:"column:label_value"`
	ValueType  string    `gorm:"column:value_type;default:TEXT;comment:标签类型: TEXT, ENUM, BOOLEAN"`
	CreatedBy  string    `gorm:"column:created_by"`
	UpdatedBy  string    `gorm:"column:updated_by"`
	Remark     string    `gorm:"column:remark;comment:备注"`
	CreatedAt  time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP;comment:创建时间"`
	UpdatedAt  time.Time `gorm:"column:updated_at;default:CURRENT_TIMESTAMP;comment:更新时间"`
	Valid      int32     `gorm:"column:valid;not null;default:1;comment:逻辑删除标记，1有效0无效"`
}

// TableName ConfInsLabel's table name
func (*ConfInsLabel) TableName() string {
	return TableNameConfInsLabel
}
