// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package po

import (
	"time"
)

const TableNameConfType = "conf_type"

// ConfType mapped from table <conf_type>
type ConfType struct {
	ID        int32     `gorm:"column:id;primaryKey;autoIncrement:true"`
	TypeCode  string    `gorm:"column:type_code;not null;comment:类型编码"`
	TypeName  string    `gorm:"column:type_name;not null;comment:类型名称"`
	Category  string    `gorm:"column:category;not null;comment:大类: INFRASTRUCTURE, APPLICATION, THIRD_PARTY, DATABASE, MIDDLEWARE"`
	Lifecycle string    `gorm:"column:lifecycle;default:PERMANENT;comment:生命周期"`
	CreatedBy string    `gorm:"column:created_by"`
	UpdatedBy string    `gorm:"column:updated_by"`
	Remark    string    `gorm:"column:remark;comment:备注"`
	CreatedAt time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP;comment:创建时间"`
	UpdatedAt time.Time `gorm:"column:updated_at;default:CURRENT_TIMESTAMP;comment:更新时间"`
	Valid     int32     `gorm:"column:valid;not null;default:1;comment:逻辑删除标记，1有效0无效"`
}

// TableName ConfType's table name
func (*ConfType) TableName() string {
	return TableNameConfType
}
