// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package po

import (
	"time"
)

const TableNameConfTypeHis = "conf_type_his"

// ConfTypeHis mapped from table <conf_type_his>
type ConfTypeHis struct {
	ID        int64     `gorm:"column:id;primaryKey;autoIncrement:true"`
	TypeID    int32     `gorm:"column:type_id;not null;comment:类型ID，关联conf_type表的id"`
	Operation string    `gorm:"column:operation;not null;comment:操作类型: CREATE, UPDATE, DELETE"`
	OldValue  string    `gorm:"column:old_value;comment:旧值"`
	NewValue  string    `gorm:"column:new_value;comment:新值"`
	CreatedBy string    `gorm:"column:created_by"`
	UpdatedBy string    `gorm:"column:updated_by"`
	Remark    string    `gorm:"column:remark;comment:备注"`
	CreatedAt time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP;comment:创建时间"`
	UpdatedAt time.Time `gorm:"column:updated_at;default:CURRENT_TIMESTAMP;comment:更新时间"`
	Valid     int32     `gorm:"column:valid;not null;default:1;comment:逻辑删除标记，1有效0无效"`
}

// TableName ConfTypeHis's table name
func (*ConfTypeHis) TableName() string {
	return TableNameConfTypeHis
}
