// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package po

import (
	"time"
)

const TableNameConf = "conf"

// Conf mapped from table <conf>
type Conf struct {
	ID            int64     `gorm:"column:id;primaryKey;autoIncrement:true"`
	SourceInsID   int64     `gorm:"column:source_ins_id;not null;comment:实体ID，关联conf_ins表的id"`
	TargetInsID   int64     `gorm:"column:target_ins_id;not null;comment:实体ID，关联conf_ins表的id"`
	RefType       string    `gorm:"column:ref_type;comment:关系类型: DEPENDS_ON, CONTAINS, CONNECTS_TO, MANAGES"`
	Sensitive     int32     `gorm:"column:sensitive;comment:是否敏感"`
	Encrypted     int32     `gorm:"column:encrypted;comment:是否加密"`
	OrderNum      int32     `gorm:"column:order_num;comment:排序"`
	CreatedBy     string    `gorm:"column:created_by"`
	UpdatedBy     string    `gorm:"column:updated_by"`
	Remark        string    `gorm:"column:remark;comment:备注"`
	CreatedAt     time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP;comment:创建时间"`
	UpdatedAt     time.Time `gorm:"column:updated_at;default:CURRENT_TIMESTAMP;comment:更新时间"`
	Valid         int32     `gorm:"column:valid;not null;default:1;comment:逻辑删除标记，1有效0无效"`
}

// TableName Conf's table name
func (*Conf) TableName() string {
	return TableNameConf
}
