// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package po

import (
	"time"
)

const TableNameConfExt = "conf_ext"

// ConfExt mapped from table <conf_ext>
type ConfExt struct {
	ID        int64     `gorm:"column:id;primaryKey;autoIncrement:true"`
	ConfID    int64     `gorm:"column:conf_id;not null;comment:原配置关系ID"`
	CreatedBy string    `gorm:"column:created_by"`
	UpdatedBy string    `gorm:"column:updated_by"`
	Remark    string    `gorm:"column:remark;comment:备注"`
	CreatedAt time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP;comment:创建时间"`
	UpdatedAt time.Time `gorm:"column:updated_at;default:CURRENT_TIMESTAMP;comment:更新时间"`
	Valid     int32     `gorm:"column:valid;not null;default:1;comment:逻辑删除标记，1有效0无效"`
}

// TableName ConfExt's table name
func (*ConfExt) TableName() string {
	return TableNameConfExt
}
