// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package po

import (
	"time"
)

const TableNameConfHis = "conf_his"

// ConfHis mapped from table <conf_his>
type ConfHis struct {
	ID        int64     `gorm:"column:id;primaryKey;autoIncrement:true"`
	ConfID    int64     `gorm:"column:conf_id;not null;comment:原配置关系ID"`
	Operation string    `gorm:"column:operation;not null;comment:操作类型: CREATE, UPDATE, DELETE"`
	OldValue  string    `gorm:"column:old_value;comment:旧值"`
	NewValue  string    `gorm:"column:new_value;comment:新值"`
	CreatedBy string    `gorm:"column:created_by"`
	UpdatedBy string    `gorm:"column:updated_by"`
	Remark    string    `gorm:"column:remark;comment:备注"`
	CreatedAt time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP;comment:创建时间"`
	UpdatedAt time.Time `gorm:"column:updated_at;default:CURRENT_TIMESTAMP;comment:更新时间"`
	Valid     int32     `gorm:"column:valid;not null;default:1;comment:逻辑删除标记，1有效0无效"`
}

// TableName ConfHis's table name
func (*ConfHis) TableName() string {
	return TableNameConfHis
}
