package cons

const (
	// conf_type_his表 常量
	CONF_TYPE_HIS_OPERATION_CREATE = "CREATE"
	CONF_TYPE_HIS_OPERATION_UPDATE = "UPDATE"
	CONF_TYPE_HIS_OPERATION_DELETE = "DELETE"

	// conf表 常量
	CONF_REF_TYPE             = "DEPENDS_ON"  // 依赖关系
	CONF_REF_TYPE_CONTAINS    = "CONTAINS"    // 包含关系/父子关系 常用
	CONF_REF_TYPE_CONNECTS_TO = "CONNECTS_TO" // 连接关系
	CONF_REF_TYPEMANAGES      = "MANAGES"     // 管理关系
	// conf_his表 常量
	CONF_HIS_OPERATION_CREATE = "CREATE"
	CONF_HIS_OPERATION_UPDATE = "UPDATE"
	CONF_HIS_OPERATION_DELETE = "DELETE"
)
