// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package po

import (
	"time"
)

const TableNameTestPerson = "test_person"

// TestPerson mapped from table <test_person>
type TestPerson struct {
	ID        int64     `gorm:"column:id;primaryKey;autoIncrement:true"`
	Name      string    `gorm:"column:name;not null;comment:名称"`
	Idcard    string    `gorm:"column:idcard;not null;comment:身份证号"`
	Age       int32     `gorm:"column:age;not null;comment:年龄"`
	Gender    string    `gorm:"column:gender;comment:枚举，1男2女"`
	Remark    string    `gorm:"column:remark;comment:备注"`
	CreatedAt time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP;comment:创建时间"`
	UpdatedAt time.Time `gorm:"column:updated_at;default:CURRENT_TIMESTAMP;comment:更新时间"`
	Valid     int32     `gorm:"column:valid;not null;default:1;comment:逻辑删除标记，1有效0无效"`
}

// TableName TestPerson's table name
func (*TestPerson) TableName() string {
	return TableNameTestPerson
}
